sudo: required

language: node

services: docker

env:
  - CHANGE_MINIKUBE_NONE_USER=true

install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.14.0
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

script:
  - minikube version
  - kubectl version
  - docker version
  - docker build -t bl/courses:0.0.1 ./courses/
  - kubectl apply -f ./courses/deployment.yaml