apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq-cluster-ip
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:management
    name: rabbitmq
    ports:
    - containerPort: 15672
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: rabbitmq
# spec:
#   replicas: 1
#   serviceName: rabbitmq
#   selector:
#     matchLabels:
#       app: rabbitmq
#   template:
#     metadata:
#       labels:
#         app: rabbitmq
#     spec:
#       containers:
#       - name: rabbitmq
#         image: rabbitmq:3-management
#         ports:
#         - containerPort: 15672
#         volumeMounts:
#         - mountPath: /var/lib/rabbitmq
#           name: rabbitmq-data
#       volumes:
#         - name: rabbitmq-data
#           hostPath:
#             path: /data/rabbitmq
#             type: DirectoryOrCreate