apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: NodePort
  ports:
  - name: http
    env:
    - name: FC_ENABLE
      value: 1
    - name: FC_SETTINGS
      value: "/etc/krakend/settings"
    - name: FC_TEMPLATES
      value: "/etc/krakend/templates"
    port: 8000
    targetPort: 8080
    protocol: TCP
  selector:
    app: krakend

---
apiVersion: v1
kind: Service
metadata:
  name: bl-krakend-cluster-ip
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: krakend
